ECommerceShop/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from ECommerceShop import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('store.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from store.views import *
urlpatterns = [
    path('', home, name="home"),
    path('cart/', cart, name="cart"),
    path('login/', login, name="login"),
    path('signup/', signup, name="signup"),
    path('orders/', orders, name="orders"),
    path('logout/',logout,name='logout'),
    path('checkout/',checkout,name='checkout'),
    path('validate_payment/',validatePayment,name='validatePayment'),

 
    path('product/<str:slug>/',show_product,name='show_product'),
    path('addtocart/<str:slug>/<str:size>',add_to_cart,name='add_to_cart'),


    
]

store/models/order.py
from enum import Flag
from django.db import models

from django.contrib.auth.models import User
from django.db.models.enums import Choices
# Create your models here.
from store.models import *



class Order(models.Model):
    orderChoices=[
        # (" we use this for operation","user/admin sees it")
        ("PENDING", "pending"),
        ("PLACED", "placed"),
        

        ("CANCELED", "canceled"),
        ("COMPLETED", "completed"),
        
    ]
    method=[
        # (" we use this for operation","user/admin sees it")
        ("COD", "cod"),
        ("ONLINE", "online"),
      
        
    ]

    order_status = models.CharField(max_length=15, choices=orderChoices)
    payment_method = models.CharField(max_length=15, choices=method)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.IntegerField(null=False)
    date = models.DateTimeField(null=False,auto_now_add=True)
    shipping_addresss = models.CharField(max_length=15, null=False)
    phone = models.CharField(max_length=10, null=False)
    


class OrderItem(models.Model):

    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    tshirt = models.ForeignKey(Tshirt,on_delete=models.CASCADE)

    size =  models.ForeignKey(SizeVarient,on_delete=models.CASCADE)

    quantity = models.IntegerField(null=False)

    price = models.IntegerField(null=False)

    date = models.DateTimeField(null=False,auto_now_add=True)

    def __str__(self):
        return self.tshirt.name
        

store/models/size.py
from enum import Flag
from django.db import models

from django.contrib.auth.models import User
from django.db.models.enums import Choices
# Create your models here.
from store.models import *

class SizeVarient(models.Model):
    price = models.IntegerField(null=False)  # not null

    # after SizeVarient record is  deleted  tshirt also need to be deleted
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)

    # we want to give choices to user/admin to select size
    SIZES = [
        # (" we use this for operation","user/admin sees it")
        # ("database Store","user ko dikhana")
        ("S", "Small"),
        ("M", "Medium"),
        ("L", "Large"),
        ("XL", "Extra large"),
        ("XXL", "Extra Extra large"),
    ]

    size = models.CharField(choices=SIZES, max_length=5)
    def __str__(self):
        return f'{self.size}'

store/views/authentication.py
from store.forms.checkout_form import CheckForm
from django.contrib.auth import authenticate, login as LoginUser, logout as logout_USER
from store.forms.authforms import CustomerCreationForm, CustomerAuthForm
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from store.models import Brand, Color, IdealFor, NeckType, Occasion, Order, OrderItem, Payment, Sleeve,Tshirt, SizeVarient, Cart
import math as m
from django.contrib.auth.decorators import login_required
from ECommerceShop.settings import API_KEY,AUTH_TOKEN
from instamojo_wrapper import Instamojo


def login(request):
    if(request.method == "GET"):
        form = CustomerAuthForm()

        # Login kelayver checkout page kadhnayasthi
        next_page = request.GET.get('next')
        if next_page is not None:

            request.session['next_page'] = next_page

        return render(request, 'store/login.html', {'form': form})

    else:
        form = CustomerAuthForm(data=request.POST)
        if(form.is_valid()):
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)

            if user:
                LoginUser(request, user)

                # When user logged in at that time session data also need to add in database - cart
                session_cart = request.session.get('cart')

                if session_cart is None:
                    session_cart = []
                else:
                    for c in session_cart:
                        size = c.get('size')
                        tshirt_id = c.get('tshirt')

                        quantity = c.get('quantity')
                        cart_obj = Cart()
                        cart_obj.sizeVarient = SizeVarient.objects.get(
                            size=size, tshirt=tshirt_id)
                        cart_obj.quantity = quantity
                        cart_obj.user = user
                        cart_obj.save()

                # We need to add this to sessions
                # {size,thirt,quantity}
                cart = Cart.objects.filter(user=user)
                session_cart = []
                for c in cart:
                    obj = {
                        "size": c.sizeVarient.size,
                        "tshirt": c.sizeVarient.tshirt.id,
                        "quantity": c.quantity
                    }
                    session_cart.append(obj)

                request.session['cart'] = session_cart

                next_page = request.session.get('next_page')
                if next_page is None:
                    next_page = "home"

                return redirect(next_page)
            else:
                return render(request, 'store/login.html', {'form': form})

        else:
            return render(request, 'store/login.html', {'form': form})


def signup(request):

    if(request.method == "GET"):
        form = CustomerCreationForm()
        context = {
            'form': form
        }
        return render(request, 'store/signup.html', context=context)

    else:  # Post - > Store Data in the database/Register user.
        form = CustomerCreationForm(request.POST)

        if(form.is_valid()):  # Store to the database
            user = form.save()
            user.email = user.username
            user.save()

            return redirect('login')

        else:  # Show user what's wrong.
            context = {
                'form': form
            }
        return render(request, 'store/signup.html', context=context)



def logout(request):
    logout_USER(request)
    return redirect('home')

store/views/cart.py
from store.forms.checkout_form import CheckForm
from django.contrib.auth import authenticate, login as LoginUser, logout as logout_USER
from store.forms.authforms import CustomerCreationForm, CustomerAuthForm
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from store.models import Brand, Color, IdealFor, NeckType, Occasion, Order, OrderItem, Payment, Sleeve,Tshirt, SizeVarient, Cart
import math as m
from django.contrib.auth.decorators import login_required
from ECommerceShop.settings import API_KEY,AUTH_TOKEN
from instamojo_wrapper import Instamojo


def cart(request):
    # IF user is not logged in we store the action in session.
    cart = request.session.get('cart')  # it return list of objects

    if cart is None:
        cart = []

    for c in cart:  # c is object
        tshirt_id = c.get('tshirt')

        # it gives that tshirt from database
        tshirt = Tshirt.objects.get(id=tshirt_id)

        # fetch size object bcz it contain price.
        c['size'] = SizeVarient.objects.get(tshirt=tshirt, size=c['size'])

        c['tshirt'] = tshirt  # id is replace with tshirt

    print(cart)

    return render(request, 'store/cart.html', context={'cart': cart})


def add_to_cart(request, slug, size):
    user = None
    if request.user.is_authenticated:
        user = request.user
    # print(slug," ",size)
    cart = request.session.get('cart')  # initiallly None

    if cart is None:
        cart = []  # it will be contain list of objects

    tshirt = Tshirt.objects.get(slug=slug)

    add_to_cart_for_anonom_user(cart, size, tshirt)

    if user is not None:
        add_cart_to_database(user, size, tshirt)

    # make cart key and assign cart list of objects to it
    request.session['cart'] = cart

    # process return_url
    # return on that url on which you click
    return_url = request.GET.get('return_url')

    return redirect(return_url)


# When User is logged in then store into the database
def add_cart_to_database(user, size, tshirt):
    size_temp = SizeVarient.objects.get(size=size, tshirt=tshirt)

    # Existin cart
    # Return list of value if contain
    existing = Cart.objects.filter(user=user, sizeVarient=size_temp)
    if len(existing) > 0:
        obj = existing[0]
        obj.quantity += 1
        obj.save()
    else:
        c = Cart()
        c.user = user
        c.sizeVarient = size_temp
        c.quantity = 1
        c.save()


# When user is not  logged in save it in session variable
def add_to_cart_for_anonom_user(cart, size, tshirt):

    flag = True
    for cart_obj in cart:
        t_id = cart_obj.get('tshirt')
        size_short = cart_obj.get('size')
        if t_id == tshirt.id and size_short == size:
            flag = False
            cart_obj['quantity'] += 1

    if flag:
        cart_obj = {
            'tshirt': tshirt.id,
            'size': size,
            'quantity': 1  # when you click on buttton quantity becomes 1.

        }
        cart.append(cart_obj)

store/views/checkout.py
from store.forms.checkout_form import CheckForm
from django.contrib.auth import authenticate, login as LoginUser, logout as logout_USER
from store.forms.authforms import CustomerCreationForm, CustomerAuthForm
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from store.models import Brand, Color, IdealFor, NeckType, Occasion, Order, OrderItem, Payment, Sleeve,Tshirt, SizeVarient, Cart
import math as m
from django.contrib.auth.decorators import login_required
from ECommerceShop.settings import API_KEY,AUTH_TOKEN
from instamojo_wrapper import Instamojo



API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/')



def total_payable_amount(cart):
    total = 0
    for c in cart:
        discount = c.get('tshirt').discount
        price = c.get('size').price
        sale_price = m.floor(price - (price * (discount / 100)))
        total_of_single_product = sale_price * c.get('quantity')
        total = total + total_of_single_product

    return total




@login_required(login_url='login')
def checkout(request):
    # Handle get Request first
    if request.method == "GET":
        obj = CheckForm()
        cart = request.session.get('cart')
        if cart is None:
            cart = []

        for c in cart:
            size_str = c.get('size')
            tshirt_id = c.get('tshirt')
            # Now Size key contain Sizevarient object that contain
            # both tshirt and price
            size_obj = SizeVarient.objects.get(size=size_str, tshirt=tshirt_id)
            c['size'] = size_obj
            c['tshirt'] = size_obj.tshirt

        return render(request, 'store/checkout.html', {'checkform': obj, 'cart': cart})


    elif request.method=="POST": # when form is submitted
        form = CheckForm(request.POST)


        # Getting Logged in user
        user= None
        if request.user.is_authenticated:
            user = request.user
        if form.is_valid():
            # payment
            cart = request.session.get('cart')
            if cart is None:
                cart=[]
            for c in cart:
                size_str = c.get('size')
                tshirt_id = c.get('tshirt')
                # Now Size key contain Sizevarient object that contain
                # both tshirt and price
                size_obj = SizeVarient.objects.get(size=size_str, tshirt=tshirt_id)
                c['size'] = size_obj
                c['tshirt'] = size_obj.tshirt



            shipping_address=form.cleaned_data.get('shipping_addresss')
            phone=form.cleaned_data.get('phone')
            payment_method=form.cleaned_data.get('payment_method')

            total=total_payable_amount(cart)

            order=Order()
            order.shipping_addresss= shipping_address
            order.total = total
            order.payment_method = payment_method
            order.phone = phone
            order.order_status = "PENDING"
            order.user = user
            order.save()

            # print(shipping_address," ",phone," ",payment_method," ", total)

            # Store all the item of the user in OrderItem table
            
            for c in cart:
                order_item= OrderItem()
                order_item.order = order
                size=c.get('size')
                tshirt=c.get('tshirt')


                

                order_item.price = m.floor(size.price -
                                         (size.price *
                                          (tshirt.discount / 100)))
                order_item.quantity = c.get('quantity')
                order_item.size = size
                order_item.tshirt = tshirt
                order_item.save()

            
            # Making payment

            response = API.payment_request_create(
                     amount=order.total,
                     purpose='Payment for Tshirts',
                     send_email=True,
                     email=user.email,
                    
                    # send_sms = True, it gives error
                    
                     buyer_name = f"{user.first_name} {user.last_name }",
                 redirect_url="http://localhost:8000/validate_payment"
            )

            payment_request_id= response['payment_request']['id']

            # By this url link client make payment . After checkout we navigateb here
            url = response['payment_request']['longurl']

            payment= Payment()
            payment.order = order
            payment.payment_request_id =  payment_request_id
            payment.save()

            return redirect(url)

        else:
            return redirect('checkout')

store/views/home.py
from django.db.models.query_utils import Q
from store.forms.checkout_form import CheckForm
from django.contrib.auth import authenticate, login as LoginUser, logout as logout_USER
from store.forms.authforms import CustomerCreationForm, CustomerAuthForm
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from store.models import Brand, Color, IdealFor, NeckType, Occasion, Order, OrderItem, Payment, Sleeve,Tshirt, SizeVarient, Cart, tshirt
import math as m
from django.contrib.auth.decorators import login_required
from ECommerceShop.settings import API_KEY,AUTH_TOKEN
# from instamojo_wrapper import Instamojo

# Pagination
from django.core.paginator import Paginator
from urllib.parse  import urlencode


def home(request):

    query=request.GET

    tshirts=[] 

    tshirts = Tshirt.objects.all()
    brand = query.get('brand')
    neckType = query.get('necktype')
    color = query.get('color')
    idealFor = query.get('idealfor')
    sleeve = query.get('sleeve')

    page= query.get('page')
    if(page is None or page==''):
        page=1

    

    

    

    if brand != '' and brand is not None:
        tshirts = tshirts.filter(brand__slug=brand)
    if neckType != '' and neckType is not None:
        tshirts = tshirts.filter(neck_type__slug=neckType)
    if color != '' and color is not None:
        tshirts = tshirts.filter(color__slug=color)
    if sleeve != '' and sleeve is not None:
        tshirts = tshirts.filter(sleeve__slug=sleeve)
    if idealFor != '' and idealFor is not None:
        tshirts = tshirts.filter(ideal_for__slug=idealFor)
    

    occasions= Occasion.objects.all()
    brands = Brand.objects.all()
    sleeves= Sleeve.objects.all()
    idealfor=IdealFor.objects.all()
    necktypes= NeckType.objects.all()
    colors = Color.objects.all()


    
    paginator = Paginator(tshirts,4) # On one page 4 object(tshirts) you want to show

    page_object=paginator.get_page(page)  # get first page that contain 4 objects

    query = request.GET.copy()
    query['page'] = ""
    # Dictinary is converted into query string.
    pageurl=urlencode(query)
    print(query)
    context = {
    'page_obj': page_object, # pass page object here
    'occasions':occasions,
    'brands':brands,
    'sleeves':sleeves,
    'idealfor':idealfor,
    'necktypes':necktypes,
    'colors':colors,
    'pageurl':pageurl
    }
    cart = request.session.get('cart')
    # print(cart)

    

    return render(request, 'store/home.html', context=context)

store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  <title>Hello, world!</title>
  <style>
    .display-5 {
      font-size: 30px;
      font-weight: 300;
    }
  </style>
</head>

<body>
  <!-- Navbar- Bootstrap - Start -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">E-commerce Tshirt</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
        </ul>


        <ul class="navbar-nav " style="  margin-left: auto;">



          <li class="nav-item">
            <a class="nav-link" href="/cart">Cart <sup class="badge alert-success">{{request.session.cart|length}}</sup></a>
          </li>
          {% if request.user.is_authenticated%}

          <li class="nav-item">
            <a class="nav-link" href="/orders">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
          {%else %}

          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/orders">Orders</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="/signup">Signup</a>
          </li>
          {% endif%}




        </ul>
      </div>
    </div>
  </nav>

  <!-- Navbar -End here -->
  {% block content%}{% endblock content%}




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>


    
</body>

</html>

store/templates/store/cart.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %}

<div class="container">
    <table class="table table-hover table-stripped">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Tshirt</th>
                <th>Size</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Sale Price</th>

                <th>Quantity</th>
                <th>Total</th>




            </tr>
        </thead>
        <tbody>

                {% for c in cart%}
                    <tr>
                        <td>{{forloop.counter }}</td>
                        <td><img height="70px" class="rounded-circle" src="{{c.tshirt.image.url}}" alt=""></td>
                        <td>{{c.tshirt.name}}</td>
                        <td>{{c.size.size}}</td>
                        <td>{{c.size.price|rupee}}</td>
                        <td>{{c.tshirt.discount}}%</td>
                        <td>{% clc_sale_price c.size.price c.tshirt.discount as sale_price %} {{sale_price|rupee}}</td>


                        <td>{{c.quantity}}</td>
                        <td>{%multiply c.quantity sale_price  as total%}{{total|rupee}}</td>



                    </tr>
                {%endfor%}

        </tbody>

        <tfoot>
            <tr>
                <th colspan='3'></th>
                <th colspan='5'>TOTAL</th>
                <th>{{cart|total_payable_amount|rupee}}</th>
            </tr>

            <tr>
                <th colspan='8'></th>
                <th><a href="/checkout" class="btn btn-success">Checkout</a></th>
            </tr>
        </tfoot>
    </table>
</div>



{% endblock %}

store/templates/store/checkout.html
{% extends "./base.html" %}

{% load crispy_forms_tags %}
{% load tshirt_tags %}
{% block content %}
<div class="container">
    <div class="p-2">
        <div class="display-5">Checkout page</div>
    </div>
    <div class="row">
        <div class="col-lg-5 border rounded shadow p-5">
            <form action="/checkout/" method="post">
                {% csrf_token %}
                {{checkform|crispy}}
                <form action="" class="form-group">
                    <input type="submit" value="Checkout" class="btn btn-outline-dark mt-4">
    
                </form>
            </form>
        </div>

        <div class="col">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Tshirt</th>
                        <th>Size</th>
                        <th>Price AfterDis</th>

                    </tr>
                </thead>
                <tbody>
                    {% for c in cart %}
                    <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{c.size.tshirt.name}}</td>
                            <td>{{c.size.size}}</td>

                            <td>{% clc_sale_price c.size.price c.size.tshirt.discount  as sp %}{{sp|rupee}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div>
                <div class="display-5">Total Payable Amount: {{cart|total_payable_amount|rupee}}</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/login.html
{% extends "./base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="w-25 p-4 mx-auto border rounded shadow mt-4 " >
    <h1 class="display-5 text-center"> Login </h1>
<hr>
    <form method="post"  action="/login/" class="bootstrap">
        {% csrf_token %}
        {{form |crispy }}

       <div class="text-center">
        <input type="submit" value="Login" class="btn btn-success mt-3 ml-auto">
       </div>
    </form>
        
</div>
{% endblock %}

store/templates/store/orders.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% load order_tags %}
{%block content%}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Items</th>
                <th>Status</th>

            </tr>
        </thead>

        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.date|date}}</td>
                <td>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Tshirt</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>

                        <tbody>

                            <!-- Order dosn't have orderitem attribute but orderitem have fk order attribute so we can access it by this method -->
                            {% for oi in order.orderitem_set.all%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><img height="60px" class="border" src="{{oi.tshirt.image.url}}" alt=""></td>
                                <td>{{oi.tshirt.name}}</td>
                                <td>{{oi.price}}</td>
                                <td>{{oi.quantity}}</td>
                                <td>{% multiply oi.quantity oi.price as result %}{{result|rupee}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>

                <td>
                    <span
                        class="badge badge-{% get_order_status_class order.order_status %}">{{order.order_status}}</span>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>



</div>
{% endblock %}

store/templates/store/payment_failed.html
{% extends "./base.html" %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Payment Failed...</h1>
    <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, quam eligendi a error ipsam commodi in. Maxime laborum ipsa alias?</p>
    
    
    
  </div>
{% endblock %}

store/templates/store/product_details.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %}

<!-- {{request.get_full_path}}   it gives full path -->

<div class="container">
    <div class="row mt-3">
        <div class="col">

            <div class="p-4 m-3">
                <div class="w-75 text-center mx-auto">
                    <img src="{{tshirt.image.url}}" class="img-fluid" alt="">
                </div>
            </div>
        </div>

        <div class="col">

            <div class="display-4">{{tshirt.name}}</div>
            <hr>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reiciendis alias optio eligendi dolorum
                sapiente molestias dolores quos omnis voluptatum, ipsam, voluptas excepturi assumenda hic consequuntur
                nihil, nisi neque enim facere.</p>

            <div class="row ">
                <div class="col">
                    <div class="p-3 display-8">
                        <span class="text-danger"><del>{{price|rupee}}</del></span>
                        &nbsp;
                        <span>{{sell_price|rupee}}</span>
                    </div>

                </div>
                <div class="col border">
                    <label for="">Select Size</label>
                    <div class="row">

                        {% for size in tshirt.sizevarient_set.all%}
                        <div class="col">
                            <a href="/product/{{tshirt.slug}}?size={{size.size}}" class="btn border btn-block btn-{% get_active_size_button_class active_size size %}">

                                {{size.size}}

                            </a>
                        </div>

                        {% endfor %}
                    </div>

                </div>

                <div class="display-5">
                    {{tshirt.discount }}% off
                </div>
                <div class="col border">
                    <div class="p-2">
                        <a href="/addtocart/{{tshirt.slug}}/{{active_size.size}}?return_url={{request.get_full_path}}" class="btn btn-outline-dark btn-block">Add to cart</a>

                        <a href="" class="btn btn-outline-dark btn-block">Buy now</a>
                    </div>
                </div>
            </div>
        </div>




    </div>
</div>
{% endblock %}

store/templates/store/signup.html
{% extends "./base.html" %}

{%  load crispy_forms_tags%}

{% block content %}


 
   
<div class="w-25 p-4 mx-auto border rounded shadow mt-4 " >
    <h1 class="display-5"> Create Account</h1>
<hr>
    <form method="post"  action="/signup/" class="bootstrap">
        {% csrf_token %}
        {{form |crispy }}

        <input type="submit" value="Register" class="btn btn-success">
    </form>
        
</div>
{% endblock content %}